use_frameworks!

platform :ios, '13.0'

target 'VisitIosHealthSdk_Example' do
  pod 'VisitIosHealthSdk', :path => '../'

  target 'VisitIosHealthSdk_Tests' do
    inherit! :search_paths

    
  end
end
